name: cat_facts
description: An app that enables you to check out some cool facts about cats
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.8
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lint: ^1.0.0
  build_runner: ^2.1.1
  json_serializable: ^6.0.1
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
